version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: smartide-anaconda-jupyter
    ports:
      tools-webide-vscode: 6800
      tools-ssh: 6822
      tools-jupyter: 8888
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - jupyter notebook /home/project --ip=* --port=8888 --NotebookApp.token='' --no-browser
      
  kube-deploy-files: "vscode-k8s-deployment.yaml" 
  docker-compose-file: "vscode-docker-compose.yaml"