
version: "3"
services:
  smartide-anaconda-jupyter:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-anaconda-v2-jupyter:latest
    restart: always
    environment:
      LOCAL_USER_PASSWORD: root123
    volumes:
      - .:/home/project
    ports:
      - 6822:22
      - 6800:3000
      - 8888:8888
    networks:
      - smartide-network  
networks:
  smartide-network:
    external: true
